checks = [
  "all",
  "-ST1020", # "comment on exported function <name> should be of the form '<name> ...'"
  "-ST1021", # "comment on exported type PtrPoll should be of the form '<name> ...' (with optional leading article)"
  "-ST1022", # "comment on exported var <name> should be of the form '<name> ...'"
  "-ST1000", # "package comment should be of the form 'Package <name>...'"
  "-ST1006" # "don't use generic names such as "this"..."
]
